### ISSUE TITLE
Isaac Gym - No Longer Supported

### ISSUE THREAD

**Issue by abdul-mannan-khan** [ntnu-arl/aerial_gym_simulator#13]
Hello,

Thank you so much for sharing this amazing work. I just have one question. From the website, it is mentioned that this software has no more support [here](https://developer.nvidia.com/isaac-gym/download). It says that 

> please consider using [Isaac Lab](https://developer.nvidia.com/isaac/sim#isaac-lab), an open-source lightweight and performance optimized application for robot learning built on the Isaac Sim platform.

Do you have any plans to shift your simulation to the supported version? If not, could you please shed some light on it please? Thank you.

**Comment by mihirk284** [comment]
Hello, 
Yes, that is correct. NVIDIA has stopped supporting Isaac Gym -- as I understand it, that means that there will not be any further development or support from their side. 

However, the simulator is still available for use and works pretty well for the use case of Aerial Gym.

We are developing a version compatible with Isaac Lab and will release a version that is built with the latest supported framework soon!
