### ISSUE TITLE
Does RL training use sampled VAE latent?

### ISSUE THREAD

**Issue by ErcBunny** [ntnu-arl/aerial_gym_simulator#17]
Hi,

Nice code and thanks for open-sourcing. I noticed the default value for ``inference_mode`` is False and ``return_sampled_latent`` is True and I was wondering if it is turned to deterministic somewhere for training. Or is it deliberately chosen to use sampled latent? Could you kindly elaborate on this?

Thank you.

**Comment by mihirk284** [comment]
Hello @ErcBunny,
Thank you :)

Currently, the RL training is not using the sampled VAE latent. The configuration you pointed out results in deterministic VAE outputs.

It is not necessary to keep it this way for training. I expect the RL policy to learn robustly even if the sampled latent is fed into it and not degrade in performance. You can set the inference_mode to False and try training as well.

Let me know if this answered your question.
Best,

**Comment by mihirk284** [comment]
To be able to answer this question, I would like to know if you are using a particular task definition? If this is the case, the simulation seed is pre-defined in the configuration file of either the learning algorithm or the `task_config` class for that task. 

If you are seeing the same latent (for example in the first timestep of multiple consecutive runs of the simulation), can you try the following? 

```python
# run these two one after another for the same image_obs tensor
image_latents1 = self.vae_model.encode(image_obs).clone()
image_latents2 = self.vae_model.encode(image_obs).clone()
```

You can put this around this line in code: https://github.com/ntnu-arl/aerial_gym_simulator/blob/070391cc30d92b76dcd3e4e41a49c8d1b60080ae/aerial_gym/task/navigation_task/navigation_task.py#L271

Comparing the outputs. Ideally, these two should be different from one-another.
Could you let me know if this happens or if they are both identical?

**Comment by ErcBunny** [comment]
@mihirk284 Thanks a lot for your confirmation.
