### ISSUE TITLE
[Request] data collection example

### ISSUE THREAD

**Issue by guglielmo610** [ntnu-arl/aerial_gym_simulator#4]
Hello,
I was wondering if it's possible to have an example of how to collect depth images and segmentation images in the environment, without rolling out the drone. I would like just to randomly position the cameras in the environment and collect data.
Thank you.

**Comment by mihirk284** [comment]
The easiest way to do this would be to "teleport" the robot. In the pre_physics_step(...), please ignore the controller or dynamics, and place the robot wherever you want randomly. This will cause the camera rendering part after this step to capture from where the robot has been placed in this step.
