### ISSUE TITLE
Cameras Extraction

### ISSUE THREAD

**Issue by mohamedamr13** [ntnu-arl/aerial_gym_simulator#5]
![image](https://github.com/ntnu-arl/aerial_gym_simulator/assets/65868639/55b70a2f-ef2b-4b28-ae0c-83cdea5aa51e)
How can I extract both the RGB and depth images ? I can only find one type of images saved in  the full_camera_array ( probably the depth image as it is 1D)

**Comment by mihirk284** [comment]
Hello, the example files provide examples using depth cameras. 

To use RGB images, please create another tensor array and use the following to access the RGB image:
`camera_image_tensor = self.gym.get_camera_image_gpu_tensor(self.sim, env_handle, cam_handle, gymapi.IMAGE_COLOR)`

This definition can be placed [here](https://github.com/ntnu-arl/aerial_gym_simulator/blob/5cc27b79cbf3caa142d63973faab0280bede5e30/aerial_gym/envs/base/aerial_robot_with_obstacles.py#L193C17-L193C123).

With this you will be able to access the RGB images captured by the camera.

**Comment by mohamedamr13** [comment]
> Hello, the example files provide examples using depth cameras.
> 
> To use RGB images, please create another tensor array and use the following to access the RGB image: `camera_image_tensor = self.gym.get_camera_image_gpu_tensor(self.sim, env_handle, cam_handle, gymapi.IMAGE_COLOR)`
> 
> This definition can be placed [here](https://github.com/ntnu-arl/aerial_gym_simulator/blob/5cc27b79cbf3caa142d63973faab0280bede5e30/aerial_gym/envs/base/aerial_robot_with_obstacles.py#L193C17-L193C123).
> 
> With this you will be able to access the RGB images captured by the camera.

Thanks a lot! @mihirk284
