### ISSUE TITLE
Load policy and run inference

### ISSUE THREAD

**Issue by mohamedamr13** [ntnu-arl/aerial_gym_simulator#6]
Is there a script to load a train network ( rl_games ) and run inference similar to the play script but with the inferred actions instead of the constant actions in the play script.

**Comment by mihirk284** [comment]
Hello, we have released a new version of the simulator last week. More features are added and better packaging with RL frameworks is provided. Please refer to this link to see how you can perform inference with the rl_games framework with the current version: https://ntnu-arl.github.io/aerial_gym_simulator/6_rl_training/#train-your-own-navigation-policies

The current package has an `rl_training` folder that provides scripts to train and test networks for control and navigation.
```bash
### Train the navigation policy for the quadrotor with velocity control
python3 runner.py --file=./ppo_aerial_quad_navigation.yaml --num_envs=1024 --headless=True

### Replay the trained policy in simulation
python3 runner.py --file=./ppo_aerial_quad_navigation.yaml --num_envs=16 --play --checkpoint=./runs/<weights_file_path>/<weights_filename>.pth
```
