### ISSUE TITLE
Reward Size Mismatch running RL games play script for a trained checkpoint

### ISSUE THREAD

**Issue by mohamedamr13** [ntnu-arl/aerial_gym_simulator#7]
I am trying to run the rl_games play script to test the policy I have trained, but I got a series of errors in rl_games that I solved till reaching this error. 

![Screenshot from 2024-04-22 13-16-05](https://github.com/ntnu-arl/aerial_gym_simulator/assets/65868639/e2b8a43e-ecea-4e47-8661-e7537f7f9a01)

File "/home/user/roshdim1/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/torch_runner.py", line 123, in run_play
    player.run()
  File "/home/user/roshdim1/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/common/player.py", line 332, in run
    cr += r
RuntimeError: The size of tensor a (8) must match the size of tensor b (13) at non-singleton dimension 2

There appears to be a mismatch in the sizes of the cr and the reward returned from the env. Is there a simpler way to run simulation of a trained checkpoint ?

This is the command I ran

python3 runner.py --play --task="quad_with_obstacles" --num_envs=8 --checkpoint=runs/quad_ppo_22-19-01-34/nn/quad_ppo.pth

**Comment by mohamedamr13** [comment]
That is the mismatch in the cr rewards and rewards vectors. Is there any reason for this mismatch. 8 is apparently the batch size. 
crshape torch.Size([8]) ]
rshape torch.Size([8, 19, 13])

**Comment by mohamedamr13** [comment]
![Screenshot from 2024-04-22 16-16-58](https://github.com/ntnu-arl/aerial_gym_simulator/assets/65868639/bd17d080-4367-4985-b9f8-12851ad6a47e)
The problem turned out to be line 185 in the env_step method in the rl_games player script. 
The correct sequence of the step method should be 
        obs, _ , rewards, dones, infos = env[0].step(actions)

Since the step method of the aerial-robot envs returns 
         self.obs_buf, self.privileged_obs_buf, self.rew_buf, self.reset_buf, self.extras
However I am still unsure if the reset_buf coincides with the dones 

is there any pointer for that ? @mihirk284

**Comment by mihirk284** [comment]
Hello @mohamedamr13  , a new version has been released for Aerial Gym now with the signals to the RL algorithm confirming to the latest Gymnasium specifications!

**Comment by mihirk284** [comment]
Closing as this issue is resolved with the latest version of the simulator
