### ISSUE TITLE
multiple drone missions

### ISSUE THREAD

**Issue by wagh311** [ntnu-arl/aerial_gym_simulator#8]
Can this code base be used to train multiple drone missions? Like multiple drone navigation?

**Comment by mihirk284** [comment]
It's possible to spawn multiple drones in the same environment.

Currently, in our case, we spawn one robot per environment and one controller per robot. This can however be changed and multiple robots can be spawned and the states of multiple robots can be sent to the controller to act upon simply by reshaping them appropriately. 

Subsequently, the controller outputs can be reshaped to command the appropriate rigid bodies in the same environment. Unfortunately, we will not be able to add support for the same in a short-enough timeframe ourselves so I would like to encourage you to try it out and revert on this issue if you need help :)

**Comment by wagh311** [comment]
Thanks for your reply, I will give it a try!
